# Generated by Django 4.1.7 on 2023-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oj", "0002_alter_suiber_createtime_alter_suiber_enrollmentyear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suiber",
            name="password",
            field=models.CharField(max_length=32, verbose_name="用户密码"),
        ),
    ]
